### ISSUE TITLE
functionnal server

### ISSUE THREAD

**Issue by otomotho** [PepeCitron/projectzomboid-server#14]
Hi @PepeCitron,
I can't have a functionnal server, my config below:

```
services:
  zomboid-server:
    image: pepecitron/projectzomboid-server
    volumes:
      - /opt/Zomboid/server-file:/data/server-file
      - /opt/Zomboid/config:/data/config
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
    environment:
      - SERVER_MAX_PLAYER=5
      - SERVER_PUBLIC_NAME=myname
      - SERVER_ADMIN_PASSWORD=mypwd
      - SERVER_PASSWORD=mypwd
      - SERVER_NAME=myname
      - SERVER_PUBLIC=true
      - MOD_NAMES="MinimalDisplayBars;fuelsideindicator;BB_CommonSense;BION_PlainMoodles;blkt_invtrack"
      - MOD_WORKSHOP_IDS="2004998206;2616986064;2875848298;3008416736;2809595776"
```

What did i did wrong ?
thanks for your help :)
